### ISSUE TITLE
Open for Consulting?

### ISSUE THREAD

**Issue by MoritzImendoerffer** [NREL/BioReactorDesign#54]
Hi, I do not know, how to get in contact other than via an issue. I would like to give your toolbox a try. I would appreciate, if I could hire you e.g. 2-3 hours to help me with get started with the meshing process and provide me with an overview of your work. I cannot pay a typical corporate fee, but I am sure we can agree on a fair amount. Is this an option for you?

**Comment by malihass** [comment]
Hi, 
thanks for reaching out!
We might want to schedule a meeting about this. 

Could you please send an email at malik . hassanaly [at] nrel. gov?

What would be useful is if you briefly explain in your email what you are trying to do, and what you have done so far with this toolbox? Then we can go from there!
I'm leaving this issue open in case you have issues reaching out via email.
