### ISSUE TITLE
Indicate how to get started with simulations to beginners in the readme

### ISSUE THREAD

**Issue by sustainapower** [NREL/BioReactorDesign#61]

**Comment by malihass** [comment]
@sustainapower Should I close this or did you want to report some issue?

**Comment by malihass** [comment]
If you want to simulate bio reactors, you can start with downloading Openfoam 9 and you can use some of our tutorial cases 

OFsolvers/tutorial_cases

I suggest to start with the  bubble column case. 

I'm reopening the issue since it is definitely something we need to improve

**Comment by malihass** [comment]
Hi @sustainapower could you please let us know if the current version of the Readme is more helpful now?
If not, could you please let us know what is unclear?
