### ISSUE TITLE
Add github action for testing openfoam tutorials

### ISSUE THREAD

**Issue by fmuni** [NREL/BioReactorDesign#67]

**Comment by malihass** [comment]
It might be also a good excuse to clean up those tutorial cases and make their name a bit more explicit  (no idea why we have 
  `loop_reactor_msh` and `loop_reactor_msh_2`) :-)

**Comment by fmuni** [comment]
@malihass I removed those tutorials in the last PR, which contains a bugfix.

**Comment by malihass** [comment]
OK thanks! linking the PR for future ref #68
